# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Bob Henderson  
tagline:          'Tech, all the time.'
description:      K-12 Tech taking it one day at a time. One mans experiences with day to day life in a K-12 school with 1:1 laptops.
url:              http://bobhenderson.org
baseurl:          /

author:
  name:           'Bob Henderson'
  url:            https://twitter.com/1nerdyguy

paginate:         5

# Custom vars
version:          2.1.0

#github:
#  repo:           https://github.com/poole/hyde
