# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Bob Henderson
tagline:          'Tech, all the time.'
description:      
url:              http://bobhenderson.org
baseurl:          /

author:
  name:           'Bob Henderson'
  url:            https://twitter.com/1nerdyguy

paginate:         5

# Custom vars
version:          2.1.0

#github:
#  repo:           https://github.com/poole/hyde
